version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=<YOUR_PG_USERNAME>
      - POSTGRES_PASSWORD=<YOUR_PG_PASSWORD>
      - POSTGRES_DB=<YOUR_PG_DB_NAME>
